apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: apache
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  externalTrafficPolicy: Local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
        - name: APACHE_RUN_USER
          value: www-data
        - name: APACHE_RUN_GROUP
          value: www-data
        volumeMounts:
        - name: apache-volume
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: apache-volume
        configMap:
          name: apache-config
          defaultMode: 420
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-config
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Welcome to Apache!</title>
    </head>
    <body>
      <h1>Welcome to Apache!</h1>
      <p>This is a dummy home page.</p>
    </body>
    </html>
