---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: my-cluster
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/nejevtic/f2l.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-cluster
  namespace: flux-system
spec:
  interval: 30s
  path: ./clusters/my-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-cluster

